name: frontend_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  app_tracking_transparency: ^2.0.6+1
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  freezed_annotation: 2.4.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.9
  source_gen: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/animation/
    - asset/etc/
    - asset/font/
    - asset/icon/
    - asset/icon/arrow/
    - asset/icon/contact/
    - asset/icon/editor/
    - asset/icon/file/
    - asset/icon/map/
    - asset/icon/media/
    - asset/icon/system/
    - asset/icon/etc/
    - asset/image/

  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/font/Pretendard-Thin.ttf
          weight: 100
        - asset: asset/font/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: asset/font/Pretendard-Light.ttf
          weight: 300
        - asset: asset/font/Pretendard-Regular.ttf
          weight: 400
        - asset: asset/font/Pretendard-Medium.ttf
          weight: 500
        - asset: asset/font/Pretendard-SemiBold.ttf
          weight: 600
        - asset: asset/font/Pretendard-Bold.ttf
          weight: 700
        - asset: asset/font/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: asset/font/Pretendard-Black.ttf
          weight: 900

# flutter_gen configuration
flutter_gen:
  output: lib/common/gen_asset/ # 추출할 경로
  line_length: 80

  # 특정 패키지와의 통합
  integrations:
    flutter_svg: true
    lottie: true